/map
/move_base_safe_server/cancel
/move_base_safe_server/feedback
/move_base_safe_server/goal
/move_base_safe_server/result
/move_base_safe_server/status
/tf
/world/occupied_cells_vis_array
/world/pcl_input
/diagnostics
